version: '26.1.4'
services:
  message-server:
    container_name: message-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: message-server:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge