# fly.toml app configuration file generated for bankinc-aged-dust-988 on 2024-07-14T20:44:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bankinc-aged-dust-988'
primary_region = 'co'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
